#to check outdated packages: flutter pub outdated
# to update packages: flutter pub upgrade --major-versions
name: school_admin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  awesome_bottom_bar: ^1.2.4
#  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_lints: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.6
  flutter_phoenix: ^1.1.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.1
  flutter_smart_dialog: ^4.9.5+1
  flutter_spinkit: ^5.2.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  liquid_pull_to_refresh: ^3.0.1
#  otp_pin_field: ^1.2.2
  path_provider: ^2.1.1
#  restart_app: ^1.2.1
  shared_preferences: ^2.2.2
#  timelines: ^0.1.0
#  device_preview: ^1.1.0
  rxdart: ^0.27.7
  easy_sidemenu: ^0.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/mawjood_splash_logo.png"
  adaptive_icon_foreground: "assets/icons/mawjood_icon_logo.png"
#
#flutter_assets:
#  assets_path: assets/icons/
#  output_path: lib/common/
#  filename: assets.dart
#  field_prefix: null
#
#  flutter_lints: ^2.0.0
#flutter_native_splash:
#  image: "assets/icons/mawjood_splash_logo.png"
#  android_12:
#    image: "assets/icons/mawjood_splash_logo.png"

flutter:
  uses-material-design: true

#  assets:
#    - assets/icons/
#    - assets/images/
#  fonts:
#    - family: MawjoodIconsData
#      fonts:
#        - asset: assets/fonts/MawjoodIconsData.ttf
flutter_intl:
  enabled: true
