// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqUoe7uNYPcIPHb4deFPm-X7GVIRv311g',
    appId: '1:497792930106:web:dd37f1d7f7ecc3acc7c003',
    messagingSenderId: '497792930106',
    projectId: 'educonnect-7716d',
    authDomain: 'educonnect-7716d.firebaseapp.com',
    storageBucket: 'educonnect-7716d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3X4RGPeUEMBMedsJxAn3ZDOFVs7aUDm8',
    appId: '1:497792930106:android:9c65bd5c8d2ad7afc7c003',
    messagingSenderId: '497792930106',
    projectId: 'educonnect-7716d',
    storageBucket: 'educonnect-7716d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn7C7QRpWtEo95u7inITtlAViU3Fk3KOE',
    appId: '1:497792930106:ios:69139dceecbd1112c7c003',
    messagingSenderId: '497792930106',
    projectId: 'educonnect-7716d',
    storageBucket: 'educonnect-7716d.appspot.com',
    iosBundleId: 'com.example.schoolAdmin',
  );
}
